### PR TITLE
Fixed fuse constructor

### PR DESCRIPTION
**Pull request by Roemer**
No idea why but vscode proposed that and it actually fixes the build.

### CODE REVIEW

**Comment by oliverschwendener** [comment]
This works when bundling but not when running the unit tests. To be honest, I have no idea why :/

**Comment by Roemer** [comment]
Yes I saw the same. Very strange.

**Comment by oliverschwendener** [comment]
I also tried to update the dependencies, but didn't work either.

**Comment by AmrBinBashir** [comment]
I think I found the solution.
1. Rnable this flag in tsconfig 
	```js
	"esModuleInterop": true
	```
2. Remove every star import in the project and refactor it from this 
	```js
	import * as <imported_name>
	```
	to this
	```js
	import <imported_name>
 	```
	for example: `import * as Fuse from "fuse.js"` to `import Fuse from "fuse.js"`

**Comment by oliverschwendener** [comment]
Thanks @AmrBinBashir!

**Comment by oliverschwendener** [comment]
It's fixed in `dev`

**Pull request closed without merging**
