### PR TITLE
group appearance options into sections for better accessibility

### PR DESCRIPTION
**Pull request by AmrBinBashir**
image

### CODE REVIEW

**Comment by oliverschwendener** [comment]
Nice! I think if we make groups, they should have a title, no?

**Comment by AmrBinBashir** [comment]
Yeah a title would be nice, I was also thinking about grouping color theme options too.

**Comment by AmrBinBashir** [comment]
I added titles and grouped color theme options too. 

image

**Comment by oliverschwendener** [comment]
Can you merge the current `dev` back to your branch? Thanks!

**Comment by AmrBinBashir** [comment]
Done, I also update missing translations but they are all from google translate.

**Comment by oliverschwendener** [comment]
There is a missing title in the last section of the appearance settings. I would put "General" or something similar in there.

image

**Comment by AmrBinBashir** [comment]
Done

**Comment by oliverschwendener** [comment]
Can you add more spacing under the title? I think it would look better.

image

**Comment by AmrBinBashir** [comment]
I didn't want to add margin to the class since it is used in different places, so I used a bulma helper class.

**Comment by oliverschwendener** [comment]
Nice!

**Pull request merged**
