### PR TITLE
feat(back-shortcut): Keyboard shortcut for previous page

### LINKED ISSUE #1195: [Feature Request] Shortcut for Go back
There are several screens with a "Go back" button. It would be handy to have a hotkey for this action.

Screens with "Go back":
- Settings
- DeepL

Common hotkeys for the "Go back" action:
- Alt+left / Cmd+left (browser way)
- Esc (intuitive way)

The hardware button "back" is working, although.

### PR DESCRIPTION
**Pull request by ke1v**
Fixes #1195

### CODE REVIEW

**Review by oliverschwendener — APPROVED** [review]
Looks good to me. Thanks!

**Review by oliverschwendener — CHANGES_REQUESTED** [review]
I just found out that this does not work as expected. If you have a dialog open (for example in the settings) and you want to close the modal with pressing "Escape" it will not only close the modal but also navigate back to the search view.

See this example:

https://github.com/user-attachments/assets/1981a85f-1f9c-4c8a-9768-351111f7c455

**Comment by oliverschwendener** [comment]
I'm closing this PR due to inactivity. Feel free to reopen if you decide to work on this again.

**Comment by ke1v** [comment]
Fixed. Turns out FluentUI doesn't stop event propagation by default for closing modals

**Review by oliverschwendener — APPROVED** [review]

**Pull request merged**
