### PR TITLE
Dev: Optimized Icons

### PR DESCRIPTION
**Pull request by mkkeck**
Icons for search engines and default icons optimized. Mainly done for Windows

### CODE REVIEW

**Comment by mkkeck** [comment]
Some improvements, mainly for Windows 10 and de_DE

**Comment by oliverschwendener** [comment]
Why does this PR contain changes from other PRs like enabling mouse support?

**Comment by mkkeck** [comment]
> Why does this PR contain changes from other PRs like enabling mouse support?

I like that PR's, but these should not go into my PR. I think there was an mistake on creating and updating my branch.

**Comment by oliverschwendener** [comment]
This PR still includes work from another PR. Can you remove those changes? Otherwise I'm not able to merge this as an "icon optimization only" change ;)

**Comment by oliverschwendener** [comment]
Closing this due to inactivity. Feel free to open it up again if any more work is done on this.

**Pull request closed without merging**
