### PR TITLE
Calculator: Custom decimal and argument separators

### PR DESCRIPTION
**Pull request by tkohlmeier**
This adds settings for custom decimal and argument separators.

Inspired by this suggestion:
https://mathjs.org/examples/browser/custom_separators.html.html

### CODE REVIEW

**Comment by tkohlmeier** [comment]
Any thoughts on this?

**Comment by tkohlmeier** [comment]
I replaced the text inputs with buttons for selection of decimal and argument separators. This prevents the user from entering separators that do not make sense, like digits or math symbols.

**Comment by oliverschwendener** [comment]
In my opinion the decimal separator should also be applied in other plugins where numbers are entered, for example the currency converter.

**Comment by tkohlmeier** [comment]
You are right, this should be a global setting.

What about the argument separator? Since it is calculator-specific., should we remove the setting and automatically set it according to the decimal separator?

**Comment by tkohlmeier** [comment]
Closing this in favor of #541

**Pull request closed without merging**
