### PR TITLE
updated mdfind command to match new call-format

### PR DESCRIPTION
**Pull request by xfirf**
Issue #308

### CODE REVIEW

**Comment by oliverschwendener** [comment]
Can you please target the `dev` branch?

**Comment by xfirf** [comment]
Yes. Sure.

**Comment by oliverschwendener** [comment]
Accoriding to [this page](https://ss64.com/osx/mdfind.html) the current solution is correct. Is there somewhere an official documentation which states that your solution is the correct way to retrieve apps?

**Comment by pthoelken** [comment]
When will this fix merged to public and released? The error is thill there on my macOS.

**Comment by xfirf** [comment]
> According to [this page](https://ss64.com/osx/mdfind.html) the current solution is correct. Is there somewhere an official documentation which states that your solution is the correct way to retrieve apps?

Sorry for the delay. I´m not refering to the official documentation but to the comment of the issue #308

**Comment by pthoelken** [comment]
@oliverschwendener maybe 
`mdfind kMDItemContentTypeTree=com.apple.application-bundle`
works on macOS 10.14.x either or did you test it already?

**Comment by pthoelken** [comment]
To serve both versions of macOS in this command is maybe the option of an if-statement which check the macOS version and execute the command depends from the if-result which should pass to the macOS version.

**Comment by oliverschwendener** [comment]
I would leave it as it is for older macOS versions and use the new format only for macOS 10.15 and newer.

**Comment by pthoelken** [comment]
Okay, when we can get the update for macOS 10.15?

**Comment by oliverschwendener** [comment]
Closing this PR because it is obsolete. See 7d6a7fc.

**Pull request closed without merging**
