### PR TITLE
Use `fs/promises` for file system utility functions

### PR DESCRIPTION
**Pull request by scomans**
Refactors some file system utility functions to use the `fs/promises` counterpart instead of callbacks.

### CODE REVIEW

**Comment by oliverschwendener** [comment]
There is no particular reason why I went for the callback variant, I just didn't know about the promises. Can you please separate the refactoring from the addition of the new feature? Thanks

**Comment by oliverschwendener** [comment]
By the way, as you're a direct collaborator on this project you can also create new branches in this repo directly if you want ;)

**Comment by scomans** [comment]
> There is no particular reason why I went for the callback variant, I just didn't know about the promises. Can you please separate the refactoring from the addition of the new feature? Thanks

Done

> By the way, as you're a direct collaborator on this project you can also create new branches in this repo directly if you want ;)

I wasn't sure if this was wanted for code outside of my extension 😅

**Comment by oliverschwendener** [comment]
Let's add some tests first, so we can be sure that we don't break anything: #1202

**Review by oliverschwendener — APPROVED** [review]

**Comment by scomans** [comment]
@oliverschwendener Should I merge this PR myself or will you do that? Not sure how you wanna handle it.

**Comment by oliverschwendener** [comment]
You can merge your PRs yourself as soon as all checks passed and it's approved 👍

**Pull request merged**
