### PR TITLE
do not make terminal hang when executing command via cmd

### PR DESCRIPTION
**Pull request by kristus123**

### CODE REVIEW

**Comment by kristus123** [comment]
https://github.com/oliverschwendener/ueli/issues/1007

**Comment by kristus123** [comment]
@oliverschwendener Is it possible to get this bug fixed in the next release ? 
And when is the next release ?

**Comment by oliverschwendener** [comment]
I am currently rewriting the whole app for v9. I think this can be solved in the shortcuts extension (that should include workflows in the future). There a user can define if their workflow should wait for the command to finish or not. Sorry for the circumstances.

**Comment by kristus123** [comment]
good to hear, and cool that you are working so actively on v9 :D

**Comment by kristus123** [comment]
Would you say the new code base will be smaller and easier for others to contribute to ?

**Comment by oliverschwendener** [comment]
I think the new code base has better separation. It has "core" modules and "extension" modules. The core modules are responsible for the core functionality and do not know anything about extensions (formerly called plugins). Then the extensions can make use of the core modules and do a very specific thing (e.g. file search, web search, browser bookmarks, whatever). The new code base should also make it much easier to work on an extension because you can do it in isolation and thus code reviews should be smaller. I'm also planning to assign contributors as owners of their extensions, so they can review future changes in the area of their responsibility.

**Pull request closed without merging**
