### PR TITLE
Separate the `favorites` and `userConfig` Stores

### PR DESCRIPTION
**Pull request by sashaweiss**
👋 Hello! First off thanks for making this app! Been migrating from Alfred, and loving it.

We (@nathanshelly and I) like to back up configs for stuff like ueli via Git: we store the config files in a repo, and symlink them into the right places for various applications to pick them up. We noticed, however, that when we did this with the `config.json` in `~/Library/Application Support/ueli` there were frequent updates to the file from changing `favorites`, which we're not interested in backing up.

After looking into the source a bit, we thought it might make sense to separate the user config store from the favorites store, since they're already logically separated in code. This PR changes the favorites store to be named `favorites.json`, and adds a migration step for clients that currently have favorites stored in `config.json` to move them to `favorites.json` going forward.

We tested the following scenarios: migrating an existing `config.json` containing favorites to a split store (migration); running with no favorites in the `config.json` or `favorites.json` (clean install); and running with config in `config.json` and favorites in `favorites.json` (normal startup). In all scenarios we saw expected behavior, i.e.: ueli loads with config and favorites as appropriate, changes to config are stored in `config.json`, and changes to favorites are stored in `favorites.json`.

Is this a change you'd be interested in taking? Are there any reasons you'd like to keep favorites and config stored in the same file?

Thanks in advance for your attention!

ueli_settings

### CODE REVIEW

**Comment by sashaweiss** [comment]
@oliverschwendener wanted to gently bump this PR. Also retargeted from `master` to `dev`, per comments on other PRs.

**Comment by sashaweiss** [comment]
rebased onto `dev`, and dropped the version bump commit (not sure how that ended up in this)

**Comment by oliverschwendener** [comment]
Thanks for your contribution! I'll look into this asap!

**Comment by nathanshelly** [comment]
totally understand you might not have much time at the moment to look into this, anything we can do to make it easier?

**Comment by oliverschwendener** [comment]
Thanks for the support, but currently I'm just busy with my personal life😅. This PR is so small, it shouldn't take long. I just have to find a few hours sometime to look into all these PRs. But thanks anyway! I'll make sure that this is part of the next release.

**Comment by sashaweiss** [comment]
No problem! Thanks for the update, and hope everything is ok!

**Pull request merged**
