### PR TITLE
Add navigation with C-n and C-p

### PR DESCRIPTION
**Pull request by sashaweiss**
Hi! Excited to start using Ueli v9. I was missing navigating using `Ctrl-n` and `Ctrl-p`, so I made a change to add event handlers for those keys to the existing list of event handlers in `Search` that already listen for arrow keys.

Please let me know what you think.

### CODE REVIEW

**Comment by oliverschwendener** [comment]
Hey Sasha, good to have you back! :) Can you explain why Ctrl+N/Ctrl+P?

**Comment by sashaweiss** [comment]
Whoops, sorry – replied from my work account. Reposting my comment:

In my experience, `Ctrl-n` and `Ctrl-p` are pretty common as "next" and "previous" commands in vim-based keymaps! For example, in vim itself you can use `Ctrl-n` and `Ctrl-p` to move through autocompletion options. I use a lot of vim-based keymaps, so I've gotten used to using them where available.

These worked in ueli v8, so my hope was that we'd be ok including them in v9 as well.

**Comment by oliverschwendener** [comment]
I was wondering if there is a way to make this more customizable. Some people just need arrow up/arrow down, some enjoy using Ctrl+n/Ctrl+p, other might have even other preferences.

**Comment by oliverschwendener** [comment]
Maybe a dedicated "Keyboard shortcuts" section somewhere in the settings would make sense, where all the keyboard shortcuts can be customized.

**Comment by oliverschwendener** [comment]
Thanks for your efforts!

I'll accept this addition, but we need more sophisticated solution in the future, as mentioned above.

**Review by oliverschwendener — APPROVED** [review]

**Comment by oliverschwendener** [comment]
Can you sign your commits?

**Comment by oliverschwendener** [comment]
Closing this due to inactivity. Feel free to reopen, make sure to sign your commits though ;)

**Comment by sashaweiss** [comment]
Hey @oliverschwendener – sorry for the inactivity. Had a productive evening, but since then been a busy summer :) I'll circle back and reopen, with updated (signed) commits. Thanks for your patience!

**Pull request closed without merging**
