### PR TITLE
Add super key support

### PR DESCRIPTION
**Pull request by themegaphoenix**
This adds the super key support for opening UELI

### CODE REVIEW

**Comment by themegaphoenix** [comment]
Issue: #353

**Comment by oliverschwendener** [comment]
Can you please target the `dev` branch?

**Comment by themegaphoenix** [comment]
@olivereisenhut i changed it to the dev branch

**Comment by oliverschwendener** [comment]
Thanks! @themegaphoenix Make sure to tag the right people ;)

**Comment by themegaphoenix** [comment]
> Thanks! @themegaphoenix Make sure to tag the right people ;)

oops :)

**Pull request merged**
