### PR TITLE
Added test to cover `\r\n` line endings

### PR DESCRIPTION
**Pull request by oliverschwendener**
This PR should add a fix to the IniFileParser in order to handle `\r\n` line endings correctly.

### CODE REVIEW

**Comment by oliverschwendener** [comment]
Hey @ke1v, I run into an issue when trying to parse an ini file from Mozilla Firefox (in order to support Firefox bookmarks). This specific ini file from Firefox on Windows has `\r\n` line endings, and the `IniFileParser` throws an error falsely. As you created the IniFileParser, could you look into the issue? I created a test in this branch, that demonstrates the issue.

**Comment by ke1v** [comment]
@oliverschwendener I've fixed the issue but I don't have write access to the IniFileParser module

**Comment by oliverschwendener** [comment]
I added you as a collaborator

**Comment by oliverschwendener** [comment]
Can you create a PR from your fork that targets this branch? I wanted to invite you as a collaborator, but had to revoke it again because I realized that all collaborators have access to repository secrets that are used in GitHub Actions, for example for the deployment.

**Comment by oliverschwendener** [comment]
You can also target the `main` branch directly if you include a test, similar to the test that I added in this branch.

**Pull request merged**
