### PR TITLE
Allow browsing search results with page up/down and fix scrolling issues

### PR DESCRIPTION
**Pull request by tkohlmeier**
This mainly addresses feature request #258. Search results can now be browsed using page up/down keys.

While working on this, I found some issues with scrolling:

- When you press arrow down till you get to the next page, the scrolling offset isn't correct. There is a little gap above the first search result:

  grafik

- When you are on the second page and go to the second result and then go one back up, ueli unnecessarily scrolls one page up.

These issues should be fixed now, too.

This also makes PR #345 obsolete.

### CODE REVIEW

**Comment by tkohlmeier** [comment]
Any thoughts on this?

**Comment by oliverschwendener** [comment]
Sorry for that massive delay, but I finally found some time to look into this 😅 

The page down action does not seem to work properly when I change the option "Max search results per page" in the appearance settings (in my example it was set to `4`). It seems to jump too far, here is a video:

(First I just used the arrow keys, and then I used the page down key)

scrolling

**Comment by tkohlmeier** [comment]
This happened because when the user enters a value for maxSearchResultsPerPage, it is saved as string instead of as number. This resulted in a string concatenation instead of an addition or subtraction.

Fixed this by parsing maxSearchResultsPerPage as number.

But would be nice if maxSearchResultsPerPage was saved as a number...

**Comment by oliverschwendener** [comment]
Ah yes you're right. Because it's an HTML input field it will be parsed into a string 🤦 I'll look into saving the property as a number. Thanks alot for your efforts, your change looks good now!

**Pull request merged**
