### PR TITLE
Adjust how Jetbrains Toolbox extension loads projects

### PR DESCRIPTION
**Pull request by scomans**
The current implementation does not show all projects. With these changes all recent project of all tools installed by the Toolbox will be shown with the icon of the tool (if no project icon is present).

### CODE REVIEW

**Review by oliverschwendener — APPROVED** [review]

**Comment by scomans** [comment]
@oliverschwendener did you test it on macOS?

**Comment by oliverschwendener** [comment]
No I didn't as I thought it doesnt need further testing. I tested it now and I get this error:

```
Error occurred in handler for 'triggerExtensionRescan': Error: ENOENT: no such file or directory, open '/Users/oliverschwendener/Library/Application Support/JetBrains/state.json'
```

**Comment by oliverschwendener** [comment]
The file is located in

```
<HOME>/Library/Application Support/JetBrains/Toolbox/state.json
```

**Comment by scomans** [comment]
> The file is located in
> 
> ```
> <HOME>/Library/Application Support/JetBrains/Toolbox/state.json
> ```
 My bad. Should have been like for Windows/Linux. Thanks for figuring that out.

**Comment by oliverschwendener** [comment]
Now the error is gone, but I don't get any results because

```typescript
await this.fileSystemUtility.pathExists(productInfoPath)
```

always results in `false`.

**Comment by scomans** [comment]
Could you show me the content of your state.json please

**Comment by oliverschwendener** [comment]
> ~/Library/Application Support/JetBrains/Toolbox/state.json

```json
{
    "version": 1,
    "appVersion": "2.4.2.32922",
    "tools": [
        {
            "channelId": "9cac...", // <= removed stuff here as I don't know if it's sensitive 🤷 
            "toolId": "PhpStorm",
            "productCode": "PS",
            "tag": "php-storm",
            "displayName": "PhpStorm",
            "displayVersion": "2024.2.1",
            "buildNumber": "242.21829.154",
            "installLocation": "/Users/oliverschwendener/Applications/PhpStorm.app",
            "launchCommand": "Contents/MacOS/phpstorm"
        }
    ]
}
```

**Comment by scomans** [comment]
Is there a `product-info.json` file in your `/Users/oliverschwendener/Applications/PhpStorm.app` folder?

**Comment by oliverschwendener** [comment]
Unfortunately there is no such file

**Comment by scomans** [comment]
And in this folder `/Users/oliverschwendener/Applications/PhpStorm.app/Contents/Resources`?

**Comment by oliverschwendener** [comment]
There it is! [product-info.json](https://github.com/user-attachments/files/16993943/product-info.json)

**Review by oliverschwendener — APPROVED** [review]
Works as expected, thanks! 💪

**Pull request merged**
