### PR TITLE
remove: settings file export

### PR DESCRIPTION
**Pull request by marvitphy**

### CODE REVIEW

**Comment by oliverschwendener** [comment]
Do you want to add some context to this PR? :)

**Comment by marvitphy** [comment]
Hello, I apologize for the lack of context.
This is the second open-source project that I have dedicated myself to understanding and proposing an implementation, so I will be extremely happy with your views on what I did, comments, criticisms, etc.

**About the extension:**
Based on other extensions, I sought to implement an extension called English Dictionary that allows the user to search for the meaning and phonetics of English words using the Free Dictionary API.

I'm looking to improve my skills as a programmer and my knowledge about git, project patterns, project structure and how to work on projects maintained by a significant number of developers.

I'm Brazilian, part of this text was translated using Google Translate.

**Comment by oliverschwendener** [comment]
> how to work on projects maintained by a significant number of developers

First, I suggest adding a meaningful title and description to the PR, so it's clear to everyone what the PR is about.

**Comment by oliverschwendener** [comment]
Then I recommend reading the [contribution guideline](https://github.com/oliverschwendener/ueli/blob/main/CONTRIBUTING.md) and adjusting your PR accordingly, for example formatting the code with prettier, which I think is currently not the case.

How to check if your code matches the formatting:
```
npm run prettier:check
```

How to format the code:
```
npm run prettier:write
```

**Comment by oliverschwendener** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
