### PR TITLE
add clickable searchResults

### LINKED ISSUE #393: Feature request: Add support for mouse interaction
did i miss something or just there's no feature to click on search results?
please make able to click on them to execute!

### PR DESCRIPTION
**Pull request by amrbashir**
Closes #393

### CODE REVIEW

**Comment by GovindKrishnan** [comment]
Will this be merged soon? Won't it bring drag & drop function? 😄

Thanks @AmrBinBashir

**Comment by AmrBinBashir** [comment]
@GovindKrishnan this doesn't include drag-n-drop unfortunately but I don't know when or if this will ever be merged, it is up to oliver.

**Comment by freedsny** [comment]
Que tal esta app: https://www.fluentsearch.net/
                            https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search/distribution_groups/daily

**Comment by ForsakenHarmony** [comment]
Why was this closed?

**Comment by amrbashir** [comment]
There was no signs of this PR getting merged anytime soon and I was/am busy and can't maintain this or the other PRs, so I just merged it in my fork and closed them. 

Anyhow Oliver is [re-writing](https://github.com/oliverschwendener/ueli/commits/beta/ueli-9)  the whole app from scratch and I think he implemented this [feature](https://github.com/oliverschwendener/ueli/blob/110f3cd38c69087479bc00728c1adcc34b030992/src/renderer/Components/SearchResult.vue#L62).

**Comment by ForsakenHarmony** [comment]
Ah, ok then

**Pull request closed without merging**
