### PR TITLE
refactor(InstantSearchResults): added the option to order instant search results

### PR DESCRIPTION
**Pull request by oliverschwendener**
The current problem is that all instant search results go after the oridnary search results. For most extensions I assume that is the right behavior but for others it would be convenient to place the instant search results at the beginning of the search result list. See [this conversation](https://github.com/oliverschwendener/ueli/pull/1279#issuecomment-2516601653) as an example.

The behavior of all existing extensions should be unchanged, as all instant search results go **after** the regular search results.

@IrishBruse @NiewView Please confirm that your extensions still behave as expected.

### CODE REVIEW

**Review by NiewView — DISMISSED** [review]

**Comment by IrishBruse** [comment]
Im seeing some duplication
image

This is the searchResult after typing `ray`
```
[
  {
    id: 'vscode-file:///home/econn/git/raylib',
    name: 'raylib',
    description: 'Folder',
    image: [Object],
    defaultAction: [Object]
  },
  {
    id: 'vscode-file:///home/econn/git/tray-notes',
    name: 'tray-notes',
    description: 'Folder',
    image: [Object],
    defaultAction: [Object]
  }
]
```

I suspect its due to this prior when typing `r`
My guess is its only removing the file one then it keeps duplicating itself?
```
    {
      id: 'vscode-file:///home/econn/git/core',
      name: 'core',
      description: 'Folder',
      image: [Object],
      defaultAction: [Object]
    },
    {
      id: 'vscode-file:///home/econn/git/core',
      name: 'core',
      description: 'File',
      image: [Object],
      defaultAction: [Object]
    },
```

**Comment by IrishBruse** [comment]
Ah seems to be a bug in my extension as its creating duplicate ids but you may still want to handle duplicates in case ill send in a pr to fix the bug to my extension

**Review by IrishBruse — APPROVED** [review]

**Comment by oliverschwendener** [comment]
> Ah seems to be a bug in my extension

@IrishBruse Does this mean it is also a problem in the current `main` branch? Or was the problem introduced with the change of this PR?

**Comment by IrishBruse** [comment]
The bug is on main but it's different this makes it worse by duplicating the broken file\folder

**Pull request merged**
