### PR TITLE
add choco instructions

### PR DESCRIPTION
**Pull request by TimB87**
I have created a chocolatey package for ueli: https://chocolatey.org/packages/ueli/

Hope that's okay!

### CODE REVIEW

**Comment by oliverschwendener** [comment]
Thanks for contributing to this project! :)

For the documentation I propose that you create a separate section called "Chocolatey" in the readme after "Installer / Zip".

**Comment by TimB87** [comment]
Thanks, no problem :)

I will rework the readme over the weekend and report back here

**Comment by TimB87** [comment]
Hi,
I have updated the README.md. What do you think?

Best regards,
Tim

**Comment by oliverschwendener** [comment]
Thanks! I would appreciate if you would replace the single quotes with backticks:

```diff
- * Type 'choco install ueli'
+ * Type `choco install ueli`
```

**Comment by TimB87** [comment]
Done, no problem :)

**Comment by oliverschwendener** [comment]
@TimB87 Will the choco package be updated automatically if I release an update here on GitHub?

**Comment by TimB87** [comment]
Nope, but I'll try to keep it up to date asap anytime! 👍

**Pull request merged**
